/**
 * Meta Conversions API relay.
 *
 * The browser pixel is routinely blocked (ad blockers, iOS tracking
 * prevention). This function re-sends the SAME event server-side using the
 * `event_id` generated by the client, so Meta deduplicates the pixel/CAPI
 * pair instead of double counting.
 *
 * PII (email / phone / name) is SHA-256 hashed here and never persisted.
 */

import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { z } from "npm:zod@3.23.8";
import { requireAdmin } from "../_shared/adminAuth.ts";

const GRAPH_VERSION = "v21.0";

const BodySchema = z.object({
  event_name: z.string().min(1).max(60),
  is_custom: z.boolean().optional().default(false),
  event_id: z.string().min(4).max(120),
  event_source_url: z.string().url().max(2048).optional(),
  action_source: z.enum(["website", "chat", "phone_call", "other"]).optional().default("website"),
  value: z.number().nonnegative().max(10_000_000).optional(),
  currency: z.string().length(3).optional(),
  source: z.string().max(120).optional(),
  email: z.string().max(255).optional(),
  phone: z.string().max(40).optional(),
  name: z.string().max(160).optional(),
  fbp: z.string().max(200).optional(),
  fbc: z.string().max(400).optional(),
  /** Admin-only QA mode: forces a Meta test_event_code and returns diagnostics. */
  dry_run: z.boolean().optional().default(false),
  test_event_code: z.string().max(60).optional(),
});


const sha256 = async (value: string): Promise<string> => {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
};

/** Meta requires normalized values before hashing. */
const normalizeEmail = (raw: string) => raw.trim().toLowerCase();
const normalizePhone = (raw: string) => {
  const digits = raw.replace(/\D/g, "");
  // Romanian local numbers (07xxxxxxxx) → E.164 digits without the leading 0.
  if (digits.length === 10 && digits.startsWith("0")) return `40${digits.slice(1)}`;
  return digits;
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  if (req.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }

  const pixelId = Deno.env.get("META_PIXEL_ID");
  const accessToken = Deno.env.get("META_CAPI_ACCESS_TOKEN");
  const envTestEventCode = Deno.env.get("META_TEST_EVENT_CODE");

  let raw: unknown;
  try {
    raw = await req.json();
  } catch {
    return json({ error: "Invalid JSON body" }, 400);
  }

  const parsed = BodySchema.safeParse(raw);
  if (!parsed.success) {
    return json({ error: parsed.error.flatten().fieldErrors }, 400);
  }
  const body = parsed.data;

  // Dry-run (QA) mode is admin-only — it can force a Meta test event.
  if (body.dry_run) {
    const auth = await requireAdmin(req, corsHeaders);
    if (!auth.ok) return auth.response!;
  }

  // Not configured yet → succeed quietly so the frontend never shows errors,
  // but a dry-run must surface the misconfiguration explicitly.
  if (!pixelId || !accessToken) {
    return body.dry_run
      ? json({
          ok: false,
          dry_run: true,
          configured: false,
          reason: "meta_capi_not_configured",
          missing: [!pixelId && "META_PIXEL_ID", !accessToken && "META_CAPI_ACCESS_TOKEN"].filter(Boolean),
        }, 200)
      : json({ skipped: "meta_capi_not_configured" });
  }

  const testEventCode = body.dry_run ? (body.test_event_code || envTestEventCode) : envTestEventCode;

  // Client IP + UA improve match quality; both come from the request itself.
  const clientIp =
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    req.headers.get("cf-connecting-ip") ||
    undefined;
  const userAgent = req.headers.get("user-agent") ?? undefined;

  const userData: Record<string, unknown> = {};

  if (body.email) userData.em = [await sha256(normalizeEmail(body.email))];
  if (body.phone) {
    const normalized = normalizePhone(body.phone);
    if (normalized.length >= 8) userData.ph = [await sha256(normalized)];
  }
  if (body.name) {
    const parts = body.name.trim().toLowerCase().split(/\s+/);
    if (parts[0]) userData.fn = [await sha256(parts[0])];
    if (parts.length > 1) userData.ln = [await sha256(parts[parts.length - 1])];
  }
  if (body.fbp) userData.fbp = body.fbp;
  if (body.fbc) userData.fbc = body.fbc;
  if (clientIp) userData.client_ip_address = clientIp;
  if (userAgent) userData.client_user_agent = userAgent;

  const payload: Record<string, unknown> = {
    data: [
      {
        event_name: body.event_name,
        event_time: Math.floor(Date.now() / 1000),
        event_id: body.event_id,
        event_source_url: body.event_source_url,
        action_source: body.action_source,
        user_data: userData,
        custom_data: {
          ...(body.value !== undefined ? { value: body.value } : {}),
          currency: body.currency ?? "EUR",
          ...(body.source ? { content_name: body.source } : {}),
          ...(body.is_custom ? { event_origin: "realtrust_web" } : {}),
        },
      },
    ],
  };
  if (testEventCode) payload.test_event_code = testEventCode;

  try {
    const response = await fetch(
      `https://graph.facebook.com/${GRAPH_VERSION}/${pixelId}/events?access_token=${encodeURIComponent(accessToken)}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      },
    );

    const text = await response.text();
    if (!response.ok) {
      console.error(`[meta-conversions] Meta rejected event [${response.status}]: ${text}`);
      return json({ error: "Meta request failed", status: response.status, details: text }, response.status);
    }

    return json({ ok: true, event_id: body.event_id, meta: text ? JSON.parse(text) : null });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[meta-conversions] unexpected error:", message);
    return json({ error: "Unexpected error", details: message }, 500);
  }
});
