/**
 * Build-time sitemap generator.
 *
 * Runs on `prebuild` (i.e. before every publish) and writes:
 *   public/sitemap-dynamic.xml  — properties, blog articles, complexes, community
 *                                 articles, pulled live from the database
 *   public/sitemap.xml          — sitemap index referencing ONLY project-domain URLs
 *
 * Why fetch the edge functions instead of querying the DB directly?
 * The `generate-sitemap` / `generate-blog-sitemap` functions already own the
 * queries, filters and image/hreflang markup, and they run with elevated
 * privileges (RLS on `blog_articles` / `properties` blocks anonymous reads).
 * We reuse their XML and only re-host it under realtrust.ro so Search Console
 * never sees cross-host sitemap entries.
 *
 * Failure is non-fatal: if the network is unavailable the previously committed
 * sitemap files are left untouched so a build never ships an empty sitemap.
 */

import { writeFileSync, existsSync, readFileSync } from "fs";
import { resolve } from "path";

const BASE_URL = "https://realtrust.ro";
const FUNCTIONS_ORIGIN = "https://mvzssjyzbwccioqvhjpo.supabase.co/functions/v1";

const SOURCES = [
  `${FUNCTIONS_ORIGIN}/generate-sitemap`,
  `${FUNCTIONS_ORIGIN}/generate-blog-sitemap`,
];

/**
 * Neighborhood landing pages (/imobiliare-timisoara/:zona) are driven by
 * src/data/neighborhoods.ts, so read the slugs straight from there — adding a
 * new zone to the app keeps the sitemap in sync automatically.
 * No <lastmod>: there is no authoritative per-page timestamp for these routes.
 */
const neighborhoodBlocks = (): string[] => {
  try {
    const src = readFileSync(resolve("src/data/neighborhoods.ts"), "utf8");
    const slugs = Array.from(src.matchAll(/^\s*slug:\s*['"]([a-z0-9-]+)['"]/gm)).map((m) => m[1]);
    return Array.from(new Set(slugs)).map(
      (slug) =>
        `  <url>\n    <loc>${BASE_URL}/imobiliare-timisoara/${slug}</loc>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>`,
    );
  } catch (err) {
    console.warn("[sitemap] could not read neighborhood slugs:", (err as Error).message);
    return [];
  }
};


/** Rewrite any legacy www / function-host <loc> to the canonical project domain. */
const canonicalizeHosts = (xml: string): string =>
  xml
    .replace(/https:\/\/www\.realtrust\.ro/g, BASE_URL)
    .replace(new RegExp(FUNCTIONS_ORIGIN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g"), BASE_URL);

const extractUrlBlocks = (xml: string): string[] => {
  const matches = xml.match(/<url>[\s\S]*?<\/url>/g);
  return matches ?? [];
};

const dedupeByLoc = (blocks: string[]): string[] => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const block of blocks) {
    const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1];
    if (!loc || seen.has(loc)) continue;
    seen.add(loc);
    out.push(block);
  }
  return out;
};

const SITEMAP_INDEX = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.ts (prebuild). All entries are served
     from the project domain so Search Console never sees a cross-host sitemap. -->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>${BASE_URL}/sitemap-static.xml</loc>
  </sitemap>
  <sitemap>
    <loc>${BASE_URL}/sitemap-dynamic.xml</loc>
  </sitemap>
</sitemapindex>
`;

const main = async () => {
  const blocks: string[] = [];

  for (const source of SOURCES) {
    try {
      const res = await fetch(source);
      if (!res.ok) {
        console.warn(`[sitemap] ${source} responded ${res.status} — skipped`);
        continue;
      }
      const xml = canonicalizeHosts(await res.text());
      blocks.push(...extractUrlBlocks(xml));
    } catch (err) {
      console.warn(`[sitemap] failed to fetch ${source}:`, (err as Error).message);
    }
  }

  const unique = dedupeByLoc(blocks);

  if (unique.length === 0) {
    const target = resolve("public/sitemap-dynamic.xml");
    console.warn(
      existsSync(target)
        ? "[sitemap] no entries fetched — keeping the existing sitemap-dynamic.xml"
        : "[sitemap] no entries fetched and no previous file — sitemap-dynamic.xml not written",
    );
  } else {
    const xml = [
      `<?xml version="1.0" encoding="UTF-8"?>`,
      `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"`,
      `        xmlns:xhtml="http://www.w3.org/1999/xhtml"`,
      `        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">`,
      ...unique,
      `</urlset>`,
      "",
    ].join("\n");
    writeFileSync(resolve("public/sitemap-dynamic.xml"), xml);
    console.log(`[sitemap] sitemap-dynamic.xml written (${unique.length} URLs)`);
  }

  writeFileSync(resolve("public/sitemap.xml"), SITEMAP_INDEX);
  console.log("[sitemap] sitemap.xml index written");
};

void main();
