-- 1) Stop alert spam from inactive/disabled jobs.
-- Per project memory: voice-agent-autopilot runs in STRICT MANUAL mode (Andrei sună doar la comandă).
UPDATE public.cron_job_registry
   SET is_active = false,
       description = COALESCE(description, '') || ' [Dezactivat: mod manual — vezi voice-agent-autopilot memory]'
 WHERE job_name = 'voice-agent-autopilot' AND is_active = true;

-- Pause GA4 import until Google Analytics Data API is enabled in GCP project 992341752506.
UPDATE public.cron_job_registry
   SET is_active = false,
       description = COALESCE(description, '') || ' [Pauzat: activează Google Analytics Data API în GCP project 992341752506, apoi reactivează]'
 WHERE job_name = 'ga4-analytics-import' AND is_active = true;

-- 2) Patch the cron-failure notification trigger:
--    - skip jobs that are not active in the registry (so deactivation actually mutes alerts)
--    - throttle to 1 notification per job per 6h per admin (dedup)
--    - use a hash anchor so the link scrolls to CronMonitor
CREATE OR REPLACE FUNCTION public.notify_admins_on_cron_failure()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  admin_rec RECORD;
  v_is_active BOOLEAN;
  v_dup INT;
BEGIN
  IF NEW.status IS NULL OR NEW.status IN ('success', 'started', 'running') THEN
    RETURN NEW;
  END IF;

  SELECT is_active INTO v_is_active
    FROM public.cron_job_registry
   WHERE job_name = NEW.job_name;

  -- If job is explicitly disabled in registry, do not spam admins.
  IF v_is_active IS NOT NULL AND v_is_active = false THEN
    RETURN NEW;
  END IF;

  FOR admin_rec IN SELECT user_id FROM public.user_roles WHERE role IN ('admin','super_admin') LOOP
    SELECT count(*) INTO v_dup
      FROM public.user_notifications
     WHERE user_id = admin_rec.user_id
       AND title = '🚨 Cron eșuat: ' || NEW.job_name
       AND created_at > now() - interval '6 hours';
    IF v_dup > 0 THEN CONTINUE; END IF;

    INSERT INTO public.user_notifications (user_id, title, message, type, action_url, action_label)
    VALUES (
      admin_rec.user_id,
      '🚨 Cron eșuat: ' || NEW.job_name,
      'Execuție cu status "' || NEW.status || '"' ||
        CASE WHEN NEW.error_message IS NOT NULL THEN ' — ' || left(NEW.error_message, 200) ELSE '' END,
      'error',
      '/admin?tab=voice-agent#cron-monitor',
      'Vezi Cron Monitor'
    );
  END LOOP;
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  RETURN NEW;
END;
$$;

-- 3) Same hash anchor for the anti-regression trigger.
CREATE OR REPLACE FUNCTION public.notify_auto_publish_regression()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_recent_statuses TEXT[];
  v_all_failed BOOLEAN;
  v_admin RECORD;
  v_recent_dup INT;
  v_err TEXT;
BEGIN
  IF NEW.job_key <> 'auto-publish-listings' THEN RETURN NEW; END IF;
  IF NEW.status NOT IN ('failed', 'timeout') THEN RETURN NEW; END IF;
  IF NEW.finished_at IS NULL THEN RETURN NEW; END IF;

  SELECT array_agg(status ORDER BY started_at DESC) INTO v_recent_statuses
  FROM (
    SELECT status, started_at FROM public.automation_runs
    WHERE job_key = 'auto-publish-listings'
      AND status IN ('success', 'failed', 'timeout')
    ORDER BY started_at DESC LIMIT 3
  ) t;

  IF v_recent_statuses IS NULL OR array_length(v_recent_statuses, 1) < 3 THEN RETURN NEW; END IF;

  v_all_failed := NOT ('success' = ANY (v_recent_statuses));
  IF NOT v_all_failed THEN RETURN NEW; END IF;

  v_err := COALESCE(NULLIF(NEW.error, ''), 'Eroare necunoscută. Verifică logurile.');
  IF length(v_err) > 500 THEN v_err := left(v_err, 500) || '…'; END IF;

  FOR v_admin IN SELECT DISTINCT user_id FROM public.user_roles WHERE role IN ('admin', 'super_admin') LOOP
    SELECT count(*) INTO v_recent_dup
    FROM public.user_notifications
    WHERE user_id = v_admin.user_id
      AND title LIKE '🚨 Alertă anti-regresie%'
      AND is_read = false
      AND created_at > now() - interval '1 hour';

    IF v_recent_dup = 0 THEN
      INSERT INTO public.user_notifications (user_id, title, message, type, action_url, action_label)
      VALUES (
        v_admin.user_id,
        '🚨 Alertă anti-regresie: auto-publish-listings eșuat',
        '3 rulări consecutive eșuate pentru job-ul auto-publish-listings. Ultima eroare: ' || v_err,
        'warning',
        '/admin?tab=voice-agent#cron-monitor',
        'Vezi Cron Monitor'
      );
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

-- 4) Cleanup existing spam notifications generated by the now-disabled / paused jobs
--    and the bogus "29682840 minute" cron-health-monitor messages.
DELETE FROM public.user_notifications
 WHERE (
        title = '🚨 Cron eșuat: ga4-analytics-import'
     OR title = '🚨 Cron eșuat: voice-agent-autopilot'
     OR (title = '⚠️ Job programat sărit' AND message LIKE '%voice-agent-autopilot%')
     OR (title = '⚠️ Job programat sărit' AND message LIKE '%ga4-analytics-import%')
  );

-- 5) Stamp last_alert_at so cron-health-monitor doesn't re-alert immediately after cleanup
UPDATE public.cron_job_registry
   SET last_alert_at = now()
 WHERE job_name IN ('voice-agent-autopilot','ga4-analytics-import');
